version: '1.0'
services:
  app:
    container_name: "triton-trt-llm"
    image: nvcr.io/nvidia/tritonserver:25.08-trtllm-python-py3
    restart: always
    volumes:
      - ..:/workspace:cached
    ports:
      - '<port>:<port>'
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
